[project]
name = "gabbie"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "faster-whisper>=1.2.1",
    "httpx>=0.28.1",
    "openai>=3.14.0",
    "setuptools<81",
    "sounddevice>=0.4.7",
    "soundfile>=0.14.0",
    "webrtcvad>=2.0.10",
]
